name: "Continuous Integration"

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
      - name: "Setup node.js"
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: "Install Angular"
        run: npm i -G @angular/cli
      - name: "Install dependencies"
        run: npm ci
      - name: "Run Build"
        run: npm run build
  unit-test:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
      - name: "Setup node.js"
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: "Install dependencies"
        run: npm ci
      - name: "Run Unit Tests"
        run: npm run test:coverage
      - name: "Upload coverage artifact"
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage/
